# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!
{fetchNuGet}: [
  (fetchNuGet {
    pname = "Argu";
    version = "6.1.1";
    hash = "sha256-tA9nFJmWvoSOo8oFV6wUuatG57a3QSW0jxADc8AzKe0=";
  })
  (fetchNuGet {
    pname = "fantomas";
    version = "6.3.15";
    hash = "sha256-Gjw7MxjUNckMWSfnOye4UTe5fZWnor6RHCls3PNsuG8=";
  })
  (fetchNuGet {
    pname = "Fantomas.Core";
    version = "6.1.1";
    hash = "sha256-FcTLHQFvKkQY/kV08jhhy/St/+FmXpp3epp/R3zUXMA=";
  })
  (fetchNuGet {
    pname = "Fantomas.FCS";
    version = "6.1.1";
    hash = "sha256-NuZ8msPEHYA8T3EYREB28F1RcNgUU8V54eg2+UttYxw=";
  })
  (fetchNuGet {
    pname = "FsCheck";
    version = "2.16.6";
    hash = "sha256-1hR2SaJTkqBzU3D955MvLNVzkQHkx0Z/QzOXZfzk2Zw=";
  })
  (fetchNuGet {
    pname = "FSharp.Core";
    version = "6.0.1";
    hash = "sha256-Ehsgt3nCJijpaVuJguC1TPVEKSkJd6PSc07D2ZQSemI=";
  })
  (fetchNuGet {
    pname = "FSharp.Core";
    version = "8.0.403";
    hash = "sha256-3XSQp7JUOU5T6gvSQXNfBF4t4gaX4J4xushH+cfM9mE=";
  })
  (fetchNuGet {
    pname = "FSharp.SystemTextJson";
    version = "0.19.13";
    hash = "sha256-iEHJJoH6FfE1Qm5VmlOANVymdbWHU2/Y4pL4if7vMTU=";
  })
  (fetchNuGet {
    pname = "FsUnit";
    version = "6.0.0";
    hash = "sha256-q87WQf6MqGhzvaQ7WkkUlCdoE94DY0CD5PaXEj64A6M=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Ref";
    version = "6.0.36";
    hash = "sha256-9jDkWbjw/nd8yqdzVTagCuqr6owJ/DUMi4BlUZT4hWU=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Runtime.linux-arm64";
    version = "6.0.36";
    hash = "sha256-JQULJyF0ivLoUU1JaFfK/HHg+/qzpN7V2RR2Cc+WlQ4=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Runtime.linux-x64";
    version = "6.0.36";
    hash = "sha256-zUsVIpV481vMLAXaLEEUpEMA9/f1HGOnvaQnaWdzlyY=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Runtime.osx-arm64";
    version = "6.0.36";
    hash = "sha256-2seqZcz0JeUjkzh3QcGa9TcJ4LUafpFjTRk+Nm8T6T0=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Runtime.osx-x64";
    version = "6.0.36";
    hash = "sha256-yxLafxiBKkvfkDggPk0P9YZIHBkDJOsFTO7/V9mEHuU=";
  })
  (fetchNuGet {
    pname = "Microsoft.Build.Tasks.Git";
    version = "1.1.1";
    hash = "sha256-PHxHmsCty8Si5dCUQSizeHkJrHa9+j2nRsg6Sz+5Za0=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeCoverage";
    version = "17.10.0";
    hash = "sha256-yQFwqVChRtIRpbtkJr92JH2i+O7xn91NGbYgnKs8G2g=";
  })
  (fetchNuGet {
    pname = "Microsoft.CSharp";
    version = "4.0.1";
    hash = "sha256-0huoqR2CJ3Z9Q2peaKD09TV3E6saYSqDGZ290K8CrH8=";
  })
  (fetchNuGet {
    pname = "Microsoft.CSharp";
    version = "4.3.0";
    hash = "sha256-a3dAiPaVuky0wpcHmpTVtAQJNGZ2v91/oArA+dpJgj8=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration";
    version = "7.0.0";
    hash = "sha256-DaTP2X8zewdBfVbuy8rKvaIOWfnUrqVzpTRR3OnLL1g=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Abstractions";
    version = "7.0.0";
    hash = "sha256-QwX//PcURR6aGhH1QFkVmSayqnHaCsFPeE9d8J9nSKs=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Binder";
    version = "7.0.0";
    hash = "sha256-dIFAourb2UlKb8YKfJDlmMzGUSBTWo5gpObos29YLuI=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection";
    version = "7.0.0";
    hash = "sha256-N2DHyHiaNvYDQ77f8HI0gE0uIX2aj/rvejVGdCXRP4g=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection.Abstractions";
    version = "7.0.0";
    hash = "sha256-55lsa2QdX1CJn1TpW1vTnkvbGXKCeE9P0O6AkW49LaA=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging";
    version = "7.0.0";
    hash = "sha256-rr/NXIZ/3FG5FYGrHD7iIIr12AksP4CnfUy1YvEdDa8=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Abstractions";
    version = "7.0.0";
    hash = "sha256-uoMkX/TnwP0YabThacTMmyxdc9itQp73CN7xEFFox74=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Configuration";
    version = "7.0.0";
    hash = "sha256-RCzW63KmAzjCBVzUVY2js05N9BHA5/AG7Dx7/veFrrg=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Console";
    version = "7.0.0";
    hash = "sha256-TmE0Ghra88EusrXPMCvWZM4Nep4SGQDm32nTPaqIGdU=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Options";
    version = "7.0.0";
    hash = "sha256-pj9I/2HpCU7bLu002/Bb5NF+ofUrJ3IyH7yVqfP8IC0=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Options.ConfigurationExtensions";
    version = "7.0.0";
    hash = "sha256-8hYZXhb/JJHrA86EdzLkP5gv50RWJIjr20LBD2C+PtI=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Primitives";
    version = "7.0.0";
    hash = "sha256-AGnfNNDvZDGZ0Er9JQxeyLoUbVH+jfXF3anFr12qk6w=";
  })
  (fetchNuGet {
    pname = "Microsoft.NET.Test.Sdk";
    version = "17.10.0";
    hash = "sha256-rkHIqB2mquNXF89XBTFpUL2z5msjTBsOcyjSBCh36I0=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Host.linux-arm64";
    version = "6.0.36";
    hash = "sha256-9lC/LYnthYhjkWWz2kkFCvlA5LJOv11jdt59SDnpdy0=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Host.linux-x64";
    version = "6.0.36";
    hash = "sha256-VFRDzx7LJuvI5yzKdGmw/31NYVbwHWPKQvueQt5xc10=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Host.osx-arm64";
    version = "6.0.36";
    hash = "sha256-DaSWwYACJGolEBuMhzDVCj/rQTdDt061xCVi+gyQnuo=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Host.osx-x64";
    version = "6.0.36";
    hash = "sha256-FrRny9EI6HKCKQbu6mcLj5w4ooSRrODD4Vj2ZMGnMd4=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Ref";
    version = "6.0.36";
    hash = "sha256-9LZgVoIFF8qNyUu8kdJrYGLutMF/cL2K82HN2ywwlx8=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Runtime.linux-arm64";
    version = "6.0.36";
    hash = "sha256-k3rxvUhCEU0pVH8KgEMtkPiSOibn+nBh+0zT2xIfId8=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Runtime.linux-x64";
    version = "6.0.36";
    hash = "sha256-U8wJ2snSDFqeAgDVLXjnniidC7Cr5aJ1/h/BMSlyu0c=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Runtime.osx-arm64";
    version = "6.0.36";
    hash = "sha256-UfLcrL2Gj/OLz0s92Oo+OCJeDpZFAcQLPLiSNND8D5Y=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Runtime.osx-x64";
    version = "6.0.36";
    hash = "sha256-0xIJYFzxdMcnCj3wzkFRQZSnQcPHzPHMzePRIOA3oJs=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "1.0.1";
    hash = "sha256-mZotlGZqtrqDSoBrZhsxFe6fuOv5/BIo0w2Z2x0zVAU=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "1.1.0";
    hash = "sha256-FeM40ktcObQJk4nMYShB61H/E8B7tIKfl9ObJ0IOcCM=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "1.1.1";
    hash = "sha256-8hLiUKvy/YirCWlFwzdejD2Db3DaXhHxT7GSZx/znJg=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Targets";
    version = "1.0.1";
    hash = "sha256-lxxw/Gy32xHi0fLgFWNj4YTFBSBkjx5l6ucmbTyf7V4=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Targets";
    version = "1.1.0";
    hash = "sha256-0AqQ2gMS8iNlYkrD+BxtIg7cXMnr9xZHtKAuN4bjfaQ=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Targets";
    version = "1.1.3";
    hash = "sha256-WLsf1NuUfRWyr7C7Rl9jiua9jximnVvzy6nk2D2bVRc=";
  })
  (fetchNuGet {
    pname = "Microsoft.SourceLink.Common";
    version = "1.1.1";
    hash = "sha256-b4FaNFneDVDbvJVX1iNyhhLTrnxUfnmyypeJr47GbXY=";
  })
  (fetchNuGet {
    pname = "Microsoft.SourceLink.GitHub";
    version = "1.1.1";
    hash = "sha256-3hc9ym5ReONp00ruCKio/Ka1gYXo/jDlUHtfK1wZPiU=";
  })
  (fetchNuGet {
    pname = "Microsoft.TestPlatform.ObjectModel";
    version = "17.10.0";
    hash = "sha256-3YjVGK2zEObksBGYg8b/CqoJgLQ1jUv4GCWNjDhLRh4=";
  })
  (fetchNuGet {
    pname = "Microsoft.TestPlatform.TestHost";
    version = "17.10.0";
    hash = "sha256-+yzP3FY6WoOosSpYnB7duZLhOPUZMQYy8zJ1d3Q4hK4=";
  })
  (fetchNuGet {
    pname = "Microsoft.Win32.Primitives";
    version = "4.3.0";
    hash = "sha256-mBNDmPXNTW54XLnPAUwBRvkIORFM7/j0D0I2SyQPDEg=";
  })
  (fetchNuGet {
    pname = "Myriad.Core";
    version = "0.8.3";
    hash = "sha256-vBOxfq8QriX/yUtaXN69rEQaY/psRNJWxqATLidrt2g=";
  })
  (fetchNuGet {
    pname = "Myriad.Sdk";
    version = "0.8.3";
    hash = "sha256-7O397WKhskKOvE3MkJT37BvxorDWngDR6gTUogtDZ2M=";
  })
  (fetchNuGet {
    pname = "Namotion.Reflection";
    version = "2.1.2";
    hash = "sha256-yLOGrEnHbXAxwTNLKsaibFrdbFLoJPpiaGjT0NYWD54=";
  })
  (fetchNuGet {
    pname = "Nerdbank.GitVersioning";
    version = "3.6.133";
    hash = "sha256-AEnBQaGGPMBmZJjZrdWARq/jY4SluuPIsKBbvfNEvLE=";
  })
  (fetchNuGet {
    pname = "Newtonsoft.Json";
    version = "13.0.1";
    hash = "sha256-K2tSVW4n4beRPzPu3rlVaBEMdGvWSv/3Q1fxaDh4Mjo=";
  })
  (fetchNuGet {
    pname = "Newtonsoft.Json";
    version = "13.0.3";
    hash = "sha256-hy/BieY4qxBWVVsDqqOPaLy1QobiIapkbrESm6v2PHc=";
  })
  (fetchNuGet {
    pname = "Newtonsoft.Json";
    version = "9.0.1";
    hash = "sha256-mYCBrgUhIJFzRuLLV9SIiIFHovzfR8Uuqfg6e08EnlU=";
  })
  (fetchNuGet {
    pname = "NJsonSchema";
    version = "10.9.0";
    hash = "sha256-7RPZmR8k9zKKMjnIx0Ci2TvQ9iYfN1moxHXQfTp7O5Q=";
  })
  (fetchNuGet {
    pname = "NUnit";
    version = "4.1.0";
    hash = "sha256-srzj0lf2ReKw41TnigZwf8rqKKNzGRRVrgN3hR/vRjo=";
  })
  (fetchNuGet {
    pname = "NUnit3TestAdapter";
    version = "4.5.0";
    hash = "sha256-ER3ogl0L5FYyc6pVVPY1ch+AQxG/WgFcnWECnYQJPes=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Collections";
    version = "4.3.0";
    hash = "sha256-4PGZqyWhZ6/HCTF2KddDsbmTTjxs2oW79YfkberDZS8=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Diagnostics.Tools";
    version = "4.3.0";
    hash = "sha256-8yLKFt2wQxkEf7fNfzB+cPUCjYn2qbqNgQ1+EeY2h/I=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Diagnostics.Tracing";
    version = "4.3.0";
    hash = "sha256-dsmTLGvt8HqRkDWP8iKVXJCS+akAzENGXKPV18W2RgI=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Globalization";
    version = "4.3.0";
    hash = "sha256-PaiITTFI2FfPylTEk7DwzfKeiA/g/aooSU1pDcdwWLU=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Globalization.Calendars";
    version = "4.3.0";
    hash = "sha256-AYh39tgXJVFu8aLi9Y/4rK8yWMaza4S4eaxjfcuEEL4=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.IO";
    version = "4.3.0";
    hash = "sha256-vej7ySRhyvM3pYh/ITMdC25ivSd0WLZAaIQbYj/6HVE=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Reflection";
    version = "4.3.0";
    hash = "sha256-ns6f++lSA+bi1xXgmW1JkWFb2NaMD+w+YNTfMvyAiQk=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Reflection.Extensions";
    version = "4.3.0";
    hash = "sha256-Y2AnhOcJwJVYv7Rp6Jz6ma0fpITFqJW+8rsw106K2X8=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Reflection.Primitives";
    version = "4.3.0";
    hash = "sha256-LkPXtiDQM3BcdYkAm5uSNOiz3uF4J45qpxn5aBiqNXQ=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Resources.ResourceManager";
    version = "4.3.0";
    hash = "sha256-9EvnmZslLgLLhJ00o5MWaPuJQlbUFcUF8itGQNVkcQ4=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Runtime";
    version = "4.3.0";
    hash = "sha256-qwhNXBaJ1DtDkuRacgHwnZmOZ1u9q7N8j0cWOLYOELM=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Runtime.Handles";
    version = "4.3.0";
    hash = "sha256-PQRACwnSUuxgVySO1840KvqCC9F8iI9iTzxNW0RcBS4=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Runtime.InteropServices";
    version = "4.3.0";
    hash = "sha256-Kaw5PnLYIiqWbsoF3VKJhy7pkpoGsUwn4ZDCKscbbzA=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Text.Encoding";
    version = "4.3.0";
    hash = "sha256-Q18B9q26MkWZx68exUfQT30+0PGmpFlDgaF0TnaIGCs=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Text.Encoding.Extensions";
    version = "4.3.0";
    hash = "sha256-6MYj0RmLh4EVqMtO/MRqBi0HOn5iG4x9JimgCCJ+EFM=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Threading.Tasks";
    version = "4.3.0";
    hash = "sha256-agdOM0NXupfHbKAQzQT8XgbI9B8hVEh+a/2vqeHctg4=";
  })
  (fetchNuGet {
    pname = "runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-LXUPLX3DJxsU1Pd3UwjO1PO9NM2elNEDXeu2Mu/vNps=";
  })
  (fetchNuGet {
    pname = "runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.2";
    hash = "sha256-EbnOqPOrAgI9eNheXLR++VnY4pHzMsEKw1dFPJ/Fl2c=";
  })
  (fetchNuGet {
    pname = "runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-qeSqaUI80+lqw5MK4vMpmO0CZaqrmYktwp6L+vQAb0I=";
  })
  (fetchNuGet {
    pname = "runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.2";
    hash = "sha256-mVg02TNvJc1BuHU03q3fH3M6cMgkKaQPBxraSHl/Btg=";
  })
  (fetchNuGet {
    pname = "runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-SrHqT9wrCBsxILWtaJgGKd6Odmxm8/Mh7Kh0CUkZVzA=";
  })
  (fetchNuGet {
    pname = "runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.2";
    hash = "sha256-g9Uiikrl+M40hYe0JMlGHe/lrR0+nN05YF64wzLmBBA=";
  })
  (fetchNuGet {
    pname = "runtime.native.System";
    version = "4.3.0";
    hash = "sha256-ZBZaodnjvLXATWpXXakFgcy6P+gjhshFXmglrL5xD5Y=";
  })
  (fetchNuGet {
    pname = "runtime.native.System.Net.Http";
    version = "4.3.0";
    hash = "sha256-c556PyheRwpYhweBjSfIwEyZHnAUB8jWioyKEcp/2dg=";
  })
  (fetchNuGet {
    pname = "runtime.native.System.Security.Cryptography.Apple";
    version = "4.3.0";
    hash = "sha256-2IhBv0i6pTcOyr8FFIyfPEaaCHUmJZ8DYwLUwJ+5waw=";
  })
  (fetchNuGet {
    pname = "runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-Jy01KhtcCl2wjMpZWH+X3fhHcVn+SyllWFY8zWlz/6I=";
  })
  (fetchNuGet {
    pname = "runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.2";
    hash = "sha256-xqF6LbbtpzNC9n1Ua16PnYgXHU0LvblEROTfK4vIxX8=";
  })
  (fetchNuGet {
    pname = "runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-wyv00gdlqf8ckxEdV7E+Ql9hJIoPcmYEuyeWb5Oz3mM=";
  })
  (fetchNuGet {
    pname = "runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.2";
    hash = "sha256-aJBu6Frcg6webvzVcKNoUP1b462OAqReF2giTSyBzCQ=";
  })
  (fetchNuGet {
    pname = "runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-zi+b4sCFrA9QBiSGDD7xPV27r3iHGlV99gpyVUjRmc4=";
  })
  (fetchNuGet {
    pname = "runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.2";
    hash = "sha256-Mpt7KN2Kq51QYOEVesEjhWcCGTqWckuPf8HlQ110qLY=";
  })
  (fetchNuGet {
    pname = "runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.Apple";
    version = "4.3.0";
    hash = "sha256-serkd4A7F6eciPiPJtUyJyxzdAtupEcWIZQ9nptEzIM=";
  })
  (fetchNuGet {
    pname = "runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-gybQU6mPgaWV3rBG2dbH6tT3tBq8mgze3PROdsuWnX0=";
  })
  (fetchNuGet {
    pname = "runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.2";
    hash = "sha256-JvMltmfVC53mCZtKDHE69G3RT6Id28hnskntP9MMP9U=";
  })
  (fetchNuGet {
    pname = "runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-VsP72GVveWnGUvS/vjOQLv1U80H2K8nZ4fDAmI61Hm4=";
  })
  (fetchNuGet {
    pname = "runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.2";
    hash = "sha256-QfFxWTVRNBhN4Dm1XRbCf+soNQpy81PsZed3x6op/bI=";
  })
  (fetchNuGet {
    pname = "runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-4yKGa/IrNCKuQ3zaDzILdNPD32bNdy6xr5gdJigyF5g=";
  })
  (fetchNuGet {
    pname = "runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.2";
    hash = "sha256-EaJHVc9aDZ6F7ltM2JwlIuiJvqM67CKRq682iVSo+pU=";
  })
  (fetchNuGet {
    pname = "runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-HmdJhhRsiVoOOCcUvAwdjpMRiyuSwdcgEv2j9hxi+Zc=";
  })
  (fetchNuGet {
    pname = "runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.2";
    hash = "sha256-PHR0+6rIjJswn89eoiWYY1DuU8u6xRJLrtjykAMuFmA=";
  })
  (fetchNuGet {
    pname = "runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-pVFUKuPPIx0edQKjzRon3zKq8zhzHEzko/lc01V/jdw=";
  })
  (fetchNuGet {
    pname = "runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.2";
    hash = "sha256-LFkh7ua7R4rI5w2KGjcHlGXLecsncCy6kDXLuy4qD/Q=";
  })
  (fetchNuGet {
    pname = "runtime.unix.Microsoft.Win32.Primitives";
    version = "4.3.0";
    hash = "sha256-LZb23lRXzr26tRS5aA0xyB08JxiblPDoA7HBvn6awXg=";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.Diagnostics.Debug";
    version = "4.3.0";
    hash = "sha256-ReoazscfbGH+R6s6jkg5sIEHWNEvjEoHtIsMbpc7+tI=";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.IO.FileSystem";
    version = "4.3.0";
    hash = "sha256-Pf4mRl6YDK2x2KMh0WdyNgv0VUNdSKVDLlHqozecy5I=";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.Net.Primitives";
    version = "4.3.0";
    hash = "sha256-pHJ+I6i16MV6m77uhTC6GPY6jWGReE3SSP3fVB59ti0=";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.Private.Uri";
    version = "4.3.0";
    hash = "sha256-c5tXWhE/fYbJVl9rXs0uHh3pTsg44YD1dJvyOA0WoMs=";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.Runtime.Extensions";
    version = "4.3.0";
    hash = "sha256-l8S9gt6dk3qYG6HYonHtdlYtBKyPb29uQ6NDjmrt3V4=";
  })
  (fetchNuGet {
    pname = "SwaggerProvider";
    version = "1.0.1";
    hash = "sha256-zCfTEXZStDfoSNkMf2EMs1uZmX3GxHLbjTqmBEebSyk=";
  })
  (fetchNuGet {
    pname = "System.Buffers";
    version = "4.3.0";
    hash = "sha256-XqZWb4Kd04960h4U9seivjKseGA/YEIpdplfHYHQ9jk=";
  })
  (fetchNuGet {
    pname = "System.Collections";
    version = "4.0.11";
    hash = "sha256-puoFMkx4Z55C1XPxNw3np8nzNGjH+G24j43yTIsDRL0=";
  })
  (fetchNuGet {
    pname = "System.Collections";
    version = "4.3.0";
    hash = "sha256-afY7VUtD6w/5mYqrce8kQrvDIfS2GXDINDh73IjxJKc=";
  })
  (fetchNuGet {
    pname = "System.Collections.Concurrent";
    version = "4.3.0";
    hash = "sha256-KMY5DfJnDeIsa13DpqvyN8NkReZEMAFnlmNglVoFIXI=";
  })
  (fetchNuGet {
    pname = "System.Configuration.ConfigurationManager";
    version = "4.4.0";
    hash = "sha256-+8wGYllXnIxRzy9dLhZFB88GoPj8ivYXS0KUfcivT8I=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.Debug";
    version = "4.0.11";
    hash = "sha256-P+rSQJVoN6M56jQbs76kZ9G3mAWFdtF27P/RijN8sj4=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.Debug";
    version = "4.3.0";
    hash = "sha256-fkA79SjPbSeiEcrbbUsb70u9B7wqbsdM9s1LnoKj0gM=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.DiagnosticSource";
    version = "4.3.0";
    hash = "sha256-OFJRb0ygep0Z3yDBLwAgM/Tkfs4JCDtsNhwDH9cd1Xw=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.DiagnosticSource";
    version = "7.0.0";
    hash = "sha256-9Wk8cHSkjKtqkN6xW7KnXoQVtF/VNbKeBq79WqDesMs=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.Tools";
    version = "4.0.1";
    hash = "sha256-vSBqTbmWXylvRa37aWyktym+gOpsvH43mwr6A962k6U=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.Tracing";
    version = "4.3.0";
    hash = "sha256-hCETZpHHGVhPYvb4C0fh4zs+8zv4GPoixagkLZjpa9Q=";
  })
  (fetchNuGet {
    pname = "System.Dynamic.Runtime";
    version = "4.0.11";
    hash = "sha256-qWqFVxuXioesVftv2RVJZOnmojUvRjb7cS3Oh3oTit4=";
  })
  (fetchNuGet {
    pname = "System.Dynamic.Runtime";
    version = "4.3.0";
    hash = "sha256-k75gjOYimIQtLBD5NDzwwi3ZMUBPRW3jmc3evDMMJbU=";
  })
  (fetchNuGet {
    pname = "System.Globalization";
    version = "4.0.11";
    hash = "sha256-rbSgc2PIEc2c2rN6LK3qCREAX3DqA2Nq1WcLrZYsDBw=";
  })
  (fetchNuGet {
    pname = "System.Globalization";
    version = "4.3.0";
    hash = "sha256-caL0pRmFSEsaoeZeWN5BTQtGrAtaQPwFi8YOZPZG5rI=";
  })
  (fetchNuGet {
    pname = "System.Globalization.Calendars";
    version = "4.3.0";
    hash = "sha256-uNOD0EOVFgnS2fMKvMiEtI9aOw00+Pfy/H+qucAQlPc=";
  })
  (fetchNuGet {
    pname = "System.Globalization.Extensions";
    version = "4.3.0";
    hash = "sha256-mmJWA27T0GRVuFP9/sj+4TrR4GJWrzNIk2PDrbr7RQk=";
  })
  (fetchNuGet {
    pname = "System.IO";
    version = "4.1.0";
    hash = "sha256-V6oyQFwWb8NvGxAwvzWnhPxy9dKOfj/XBM3tEC5aHrw=";
  })
  (fetchNuGet {
    pname = "System.IO";
    version = "4.3.0";
    hash = "sha256-ruynQHekFP5wPrDiVyhNiRIXeZ/I9NpjK5pU+HPDiRY=";
  })
  (fetchNuGet {
    pname = "System.IO.FileSystem";
    version = "4.0.1";
    hash = "sha256-4VKXFgcGYCTWVXjAlniAVq0dO3o5s8KHylg2wg2/7k0=";
  })
  (fetchNuGet {
    pname = "System.IO.FileSystem";
    version = "4.3.0";
    hash = "sha256-vNIYnvlayuVj0WfRfYKpDrhDptlhp1pN8CYmlVd2TXw=";
  })
  (fetchNuGet {
    pname = "System.IO.FileSystem.Primitives";
    version = "4.0.1";
    hash = "sha256-IpigKMomqb6pmYWkrlf0ZdpILtRluX2cX5sOKVW0Feg=";
  })
  (fetchNuGet {
    pname = "System.IO.FileSystem.Primitives";
    version = "4.3.0";
    hash = "sha256-LMnfg8Vwavs9cMnq9nNH8IWtAtSfk0/Fy4s4Rt9r1kg=";
  })
  (fetchNuGet {
    pname = "System.Linq";
    version = "4.1.0";
    hash = "sha256-ZQpFtYw5N1F1aX0jUK3Tw+XvM5tnlnshkTCNtfVA794=";
  })
  (fetchNuGet {
    pname = "System.Linq";
    version = "4.3.0";
    hash = "sha256-R5uiSL3l6a3XrXSSL6jz+q/PcyVQzEAByiuXZNSqD/A=";
  })
  (fetchNuGet {
    pname = "System.Linq.Expressions";
    version = "4.1.0";
    hash = "sha256-7zqB+FXgkvhtlBzpcZyd81xczWP0D3uWssyAGw3t7b4=";
  })
  (fetchNuGet {
    pname = "System.Linq.Expressions";
    version = "4.3.0";
    hash = "sha256-+3pvhZY7rip8HCbfdULzjlC9FPZFpYoQxhkcuFm2wk8=";
  })
  (fetchNuGet {
    pname = "System.Memory";
    version = "4.5.5";
    hash = "sha256-EPQ9o1Kin7KzGI5O3U3PUQAZTItSbk9h/i4rViN3WiI=";
  })
  (fetchNuGet {
    pname = "System.Net.Http";
    version = "4.3.4";
    hash = "sha256-FMoU0K7nlPLxoDju0NL21Wjlga9GpnAoQjsFhFYYt00=";
  })
  (fetchNuGet {
    pname = "System.Net.Primitives";
    version = "4.3.0";
    hash = "sha256-MY7Z6vOtFMbEKaLW9nOSZeAjcWpwCtdO7/W1mkGZBzE=";
  })
  (fetchNuGet {
    pname = "System.ObjectModel";
    version = "4.0.12";
    hash = "sha256-MudZ/KYcvYsn2cST3EE049mLikrNkmE7QoUoYKKby+s=";
  })
  (fetchNuGet {
    pname = "System.ObjectModel";
    version = "4.3.0";
    hash = "sha256-gtmRkWP2Kwr3nHtDh0yYtce38z1wrGzb6fjm4v8wN6Q=";
  })
  (fetchNuGet {
    pname = "System.Private.Uri";
    version = "4.3.0";
    hash = "sha256-fVfgcoP4AVN1E5wHZbKBIOPYZ/xBeSIdsNF+bdukIRM=";
  })
  (fetchNuGet {
    pname = "System.Reflection";
    version = "4.1.0";
    hash = "sha256-idZHGH2Yl/hha1CM4VzLhsaR8Ljo/rV7TYe7mwRJSMs=";
  })
  (fetchNuGet {
    pname = "System.Reflection";
    version = "4.3.0";
    hash = "sha256-NQSZRpZLvtPWDlvmMIdGxcVuyUnw92ZURo0hXsEshXY=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit";
    version = "4.0.1";
    hash = "sha256-F1MvYoQWHCY89/O4JBwswogitqVvKuVfILFqA7dmuHk=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit";
    version = "4.3.0";
    hash = "sha256-5LhkDmhy2FkSxulXR+bsTtMzdU3VyyuZzsxp7/DwyIU=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit.ILGeneration";
    version = "4.0.1";
    hash = "sha256-YG+eJBG5P+5adsHiw/lhJwvREnvdHw6CJyS8ZV4Ujd0=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit.ILGeneration";
    version = "4.3.0";
    hash = "sha256-mKRknEHNls4gkRwrEgi39B+vSaAz/Gt3IALtS98xNnA=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit.Lightweight";
    version = "4.0.1";
    hash = "sha256-uVvNOnL64CPqsgZP2OLqNmxdkZl6Q0fTmKmv9gcBi+g=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit.Lightweight";
    version = "4.3.0";
    hash = "sha256-rKx4a9yZKcajloSZHr4CKTVJ6Vjh95ni+zszPxWjh2I=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Extensions";
    version = "4.0.1";
    hash = "sha256-NsfmzM9G/sN3H8X2cdnheTGRsh7zbRzvegnjDzDH/FQ=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Extensions";
    version = "4.3.0";
    hash = "sha256-mMOCYzUenjd4rWIfq7zIX9PFYk/daUyF0A8l1hbydAk=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Metadata";
    version = "1.6.0";
    hash = "sha256-JJfgaPav7UfEh4yRAQdGhLZF1brr0tUWPl6qmfNWq/E=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Primitives";
    version = "4.0.1";
    hash = "sha256-SFSfpWEyCBMAOerrMCOiKnpT+UAWTvRcmoRquJR6Vq0=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Primitives";
    version = "4.3.0";
    hash = "sha256-5ogwWB4vlQTl3jjk1xjniG2ozbFIjZTL9ug0usZQuBM=";
  })
  (fetchNuGet {
    pname = "System.Reflection.TypeExtensions";
    version = "4.1.0";
    hash = "sha256-R0YZowmFda+xzKNR4kKg7neFoE30KfZwp/IwfRSKVK4=";
  })
  (fetchNuGet {
    pname = "System.Reflection.TypeExtensions";
    version = "4.3.0";
    hash = "sha256-4U4/XNQAnddgQIHIJq3P2T80hN0oPdU2uCeghsDTWng=";
  })
  (fetchNuGet {
    pname = "System.Resources.ResourceManager";
    version = "4.0.1";
    hash = "sha256-cZ2/3/fczLjEpn6j3xkgQV9ouOVjy4Kisgw5xWw9kSw=";
  })
  (fetchNuGet {
    pname = "System.Resources.ResourceManager";
    version = "4.3.0";
    hash = "sha256-idiOD93xbbrbwwSnD4mORA9RYi/D/U48eRUsn/WnWGo=";
  })
  (fetchNuGet {
    pname = "System.Runtime";
    version = "4.1.0";
    hash = "sha256-FViNGM/4oWtlP6w0JC0vJU+k9efLKZ+yaXrnEeabDQo=";
  })
  (fetchNuGet {
    pname = "System.Runtime";
    version = "4.3.0";
    hash = "sha256-51813WXpBIsuA6fUtE5XaRQjcWdQ2/lmEokJt97u0Rg=";
  })
  (fetchNuGet {
    pname = "System.Runtime";
    version = "4.3.1";
    hash = "sha256-R9T68AzS1PJJ7v6ARz9vo88pKL1dWqLOANg4pkQjkA0=";
  })
  (fetchNuGet {
    pname = "System.Runtime.CompilerServices.Unsafe";
    version = "6.0.0";
    hash = "sha256-bEG1PnDp7uKYz/OgLOWs3RWwQSVYm+AnPwVmAmcgp2I=";
  })
  (fetchNuGet {
    pname = "System.Runtime.Extensions";
    version = "4.1.0";
    hash = "sha256-X7DZ5CbPY7jHs20YZ7bmcXs9B5Mxptu/HnBUvUnNhGc=";
  })
  (fetchNuGet {
    pname = "System.Runtime.Extensions";
    version = "4.3.0";
    hash = "sha256-wLDHmozr84v1W2zYCWYxxj0FR0JDYHSVRaRuDm0bd/o=";
  })
  (fetchNuGet {
    pname = "System.Runtime.Handles";
    version = "4.0.1";
    hash = "sha256-j2QgVO9ZOjv7D1het98CoFpjoYgxjupuIhuBUmLLH7w=";
  })
  (fetchNuGet {
    pname = "System.Runtime.Handles";
    version = "4.3.0";
    hash = "sha256-KJ5aXoGpB56Y6+iepBkdpx/AfaJDAitx4vrkLqR7gms=";
  })
  (fetchNuGet {
    pname = "System.Runtime.InteropServices";
    version = "4.1.0";
    hash = "sha256-QceAYlJvkPRJc/+5jR+wQpNNI3aqGySWWSO30e/FfQY=";
  })
  (fetchNuGet {
    pname = "System.Runtime.InteropServices";
    version = "4.3.0";
    hash = "sha256-8sDH+WUJfCR+7e4nfpftj/+lstEiZixWUBueR2zmHgI=";
  })
  (fetchNuGet {
    pname = "System.Runtime.Numerics";
    version = "4.3.0";
    hash = "sha256-P5jHCgMbgFMYiONvzmaKFeOqcAIDPu/U8bOVrNPYKqc=";
  })
  (fetchNuGet {
    pname = "System.Runtime.Serialization.Primitives";
    version = "4.1.1";
    hash = "sha256-80B05oxJbPLGq2pGOSl6NlZvintX9A1CNpna2aN0WRA=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Algorithms";
    version = "4.3.0";
    hash = "sha256-tAJvNSlczYBJ3Ed24Ae27a55tq/n4D3fubNQdwcKWA8=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Cng";
    version = "4.3.0";
    hash = "sha256-u17vy6wNhqok91SrVLno2M1EzLHZm6VMca85xbVChsw=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Csp";
    version = "4.3.0";
    hash = "sha256-oefdTU/Z2PWU9nlat8uiRDGq/PGZoSPRgkML11pmvPQ=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Encoding";
    version = "4.3.0";
    hash = "sha256-Yuge89N6M+NcblcvXMeyHZ6kZDfwBv3LPMDiF8HhJss=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-DL+D2sc2JrQiB4oAcUggTFyD8w3aLEjJfod5JPe+Oz4=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Primitives";
    version = "4.3.0";
    hash = "sha256-fnFi7B3SnVj5a+BbgXnbjnGNvWrCEU6Hp/wjsjWz318=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.ProtectedData";
    version = "4.4.0";
    hash = "sha256-Ri53QmFX8I8UH0x4PikQ1ZA07ZSnBUXStd5rBfGWFOE=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.X509Certificates";
    version = "4.3.0";
    hash = "sha256-MG3V/owDh273GCUPsGGraNwaVpcydupl3EtPXj6TVG0=";
  })
  (fetchNuGet {
    pname = "System.Text.Encoding";
    version = "4.0.11";
    hash = "sha256-PEailOvG05CVgPTyKLtpAgRydlSHmtd5K0Y8GSHY2Lc=";
  })
  (fetchNuGet {
    pname = "System.Text.Encoding";
    version = "4.3.0";
    hash = "sha256-GctHVGLZAa/rqkBNhsBGnsiWdKyv6VDubYpGkuOkBLg=";
  })
  (fetchNuGet {
    pname = "System.Text.Encoding.Extensions";
    version = "4.0.11";
    hash = "sha256-+kf7J3dEhgCbnCM5vHYlsTm5/R/Ud0Jr6elpHm922iI=";
  })
  (fetchNuGet {
    pname = "System.Text.Encoding.Extensions";
    version = "4.3.0";
    hash = "sha256-vufHXg8QAKxHlujPHHcrtGwAqFmsCD6HKjfDAiHyAYc=";
  })
  (fetchNuGet {
    pname = "System.Text.Encodings.Web";
    version = "7.0.0";
    hash = "sha256-tF8qt9GZh/nPy0mEnj6nKLG4Lldpoi/D8xM5lv2CoYQ=";
  })
  (fetchNuGet {
    pname = "System.Text.Encodings.Web";
    version = "8.0.0";
    hash = "sha256-IUQkQkV9po1LC0QsqrilqwNzPvnc+4eVvq+hCvq8fvE=";
  })
  (fetchNuGet {
    pname = "System.Text.Json";
    version = "7.0.0";
    hash = "sha256-198zqA6NR4lGCKgpdy/ptkS0jsYRT6KUjewtfi4Fi2k=";
  })
  (fetchNuGet {
    pname = "System.Text.Json";
    version = "8.0.5";
    hash = "sha256-yKxo54w5odWT6nPruUVsaX53oPRe+gKzGvLnnxtwP68=";
  })
  (fetchNuGet {
    pname = "System.Text.RegularExpressions";
    version = "4.1.0";
    hash = "sha256-x6OQN6MCN7S0fJ6EFTfv4rczdUWjwuWE9QQ0P6fbh9c=";
  })
  (fetchNuGet {
    pname = "System.Threading";
    version = "4.0.11";
    hash = "sha256-mob1Zv3qLQhQ1/xOLXZmYqpniNUMCfn02n8ZkaAhqac=";
  })
  (fetchNuGet {
    pname = "System.Threading";
    version = "4.3.0";
    hash = "sha256-ZDQ3dR4pzVwmaqBg4hacZaVenQ/3yAF/uV7BXZXjiWc=";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks";
    version = "4.0.11";
    hash = "sha256-5SLxzFg1df6bTm2t09xeI01wa5qQglqUwwJNlQPJIVs=";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks";
    version = "4.3.0";
    hash = "sha256-Z5rXfJ1EXp3G32IKZGiZ6koMjRu0n8C1NGrwpdIen4w=";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks.Extensions";
    version = "4.0.0";
    hash = "sha256-+YdcPkMhZhRbMZHnfsDwpNbUkr31X7pQFGxXYcAPZbE=";
  })
  (fetchNuGet {
    pname = "System.Xml.ReaderWriter";
    version = "4.0.11";
    hash = "sha256-haZAFFQ9Sl2DhfvEbdx2YRqKEoxNMU5STaqpMmXw0zA=";
  })
  (fetchNuGet {
    pname = "System.Xml.XDocument";
    version = "4.0.11";
    hash = "sha256-KPz1kxe0RUBM+aoktJ/f9p51GudMERU8Pmwm//HdlFg=";
  })
  (fetchNuGet {
    pname = "WoofWare.Myriad.Plugins";
    version = "3.1.1";
    hash = "sha256-kAQCi6zyFxPfDOIXn3dKg4M9wJYCpW7/Z8Ic7+yuFNg=";
  })
  (fetchNuGet {
    pname = "WoofWare.Myriad.Plugins.Attributes";
    version = "3.6.2";
    hash = "sha256-Z8j9it7dC9i/SuKo133KZywBkzHL7JtAWFojA1jLpAc=";
  })
]
